title: "Nir Ellor Waizner"
tagline: "From Research to Hands-On"
description: "AI · Vision · Systems"
theme: jekyll-theme-cayman
url: "https://nirellor.github.io"
github_username: nirellor
show_downloads: false

